from pydantic import BaseModel, Field

# To prepare list of URL sources from response
class Source(BaseModel):
    """Schema for a Source used by the agent"""
    url:str = Field(description="The url of the source")
    
# To prepare agent response and list of URL
class AgentResponse(BaseModel):
    """Schema for agent response generated with answer and source"""
    answer:str = Field(description="Agent's answer to the query")
    sources:list[Source] = Field(default_factory= list,description="list of sources generated by agent")