from langchain_core.tools import tool
from tavily import TavilyClient
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage
from langchain.agents import create_agent
from dotenv import load_dotenv

load_dotenv()

# To prepare list of URL sources from response
class Source(BaseModel):
    """Schema for a Source used by the agent"""
    url:str = Field(description="The url of the source")
    
# To prepare agent response and list of URL
class AgentResponse(BaseModel):
    """Schema for agent response generated with answer and source"""
    answer:str = Field(description="Agent's answer to the query")
    sources:list[Source] = Field(default_factory= list,description="list of sources generated by agent")

class SearchAgent:
    def __init__(self, name):
        self.name = name

@tool
def search(query: str) -> str:
    """
    Search for information about the given query.
    Args:
        query (str): The search query.
    Returns:
        str: The search results.
    """
    print("Searching for information about:", query)
    return TavilyClient().search(query=query)

def main():
    print("Search Agent using LangChain!!")
    query = input("Ask a question : ")
    
    # LLM initialization
    llm = ChatOpenAI(temperature=0, model="gpt-4")
    # Agent creation
    agent = create_agent(model= llm, tools=[search], response_format=AgentResponse)
    # Invoking the agent with the user's query
    response = agent.invoke({"messages" : [HumanMessage(content=query)]})
    print(response["answer"])
    print(response["sources"])
    
if __name__ == "__main__":
    main()