[project]
name = "deep-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "deepagents>=0.7.17",
    "dotenv>=0.9.9",
    "isort>=9.0.1",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-openai>=1.6.3",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.12",
    "tavily-python>=0.8.4",
]
