from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableSequence
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

load_dotenv()

llm = ChatOllama(
    model="llama3", num_thread=4, num_ctx=4096, num_predict=2048, temperature=0
)


class FixGrammerMistake(BaseModel):
    """Schema for fixed grammer content obtained by LLM"""

    fixed_grammer_content: str = Field("Fixed grammer content generated by LLM")


fix_grammer_structured_output = llm.with_structured_output(FixGrammerMistake)

from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
                You are an expert Resume Proofreader and Editor. Your sole task is to apply specific grammar fixes to a resume.

                CRITICAL INSTRUCTIONS:
                1. FIX ONLY PRESCRIBED ERRORS: Apply corrections strictly based on the provided list of identified errors.
                2. PRESERVE ORIGINAL FORMATTING: Maintain the original sentence structure, tone, dynamic action verbs, and resume styling (e.g., bullet points, past/present tense choices for roles).
                3. DO NOT OVER-EDIT: Do not rephrase, rewrite, or attempt to "improve" text that was not flagged in the error list.
                4. CLEAN OUTPUT: Return ONLY the corrected version of the text. Do not include commentary, intro, or wrap-up notes.
            """,
        ),
        (
            "human",
            """
                Correct the text below using the specified list of errors.

                Original Text:
                {error_content}
                        
                Identified Errors, Reason and Equivalent correct words:
                {grammer_errors}
            """,
        ),
    ]
)

fix_grammer_grader: RunnableSequence = prompt | fix_grammer_structured_output
